### ISSUE TITLE
JSON Converter not converting

### ISSUE THREAD

**Issue by mindrunner** [prkumar/uplink#105] opened 2018-08-17 21:25 UTC
The following example gives this output:

> <class 'requests.models.Response'>
> Ran 2 tests in 0.743s
> OK
> <class 'requests.models.Response'>

Expected output:
> <class '....JokeSchema'>
> Ran 2 tests in 0.743s
> OK
> <class '....JokeSchema'>

Am I missing something here? Or is this a bug?

```
from marshmallow import Schema, fields

class Joke(object):
    def __init__(self, id, url, icon_url, value):
        self.id = id
        self.url = url
        self.icon_url = icon_url
        self.value = value

class JokeSchema(Schema):
    id = fields.Str()
    url = fields.Str()
    icon_url = fields.Str()
    value = fields.Float()
```
```
import typing
from uplink import Consumer, \
    get, \
    returns

from rest_client.lib.model.chuck.Joke import JokeSchema

BASE_URL = "https://api.chucknorris.io/jokes/"

class Chuck(Consumer):
    def __init__(self):
        super().__init__(base_url=BASE_URL)

    @get("random")
    @returns.json
    def get_random_joke(self) -> JokeSchema:
        """Get a random Joke."""

    @get("categories")
    def list_categories(self) -> typing.List[str]:
        """Fetch all categories"""
```
```
import unittest
from rest_client.lib.Chuck import Chuck

class ChuckTest(unittest.TestCase):

    chuck = Chuck()

    def test_random_joke(self):
        joke = self.chuck.get_random_joke()
        print(type(joke))

    def test_categories(self):
        categories = self.chuck.list_categories()
        print(type(categories))

if __name__ == '__main__':
    unittest.main()
```

**Comment by prkumar** [comment] 2018-08-18 06:29
@mindrunner - by the way, thanks for providing an example for how to reproduce the issue! It really helps!

**Comment by mindrunner** [comment] 2018-08-18 10:35
@prkumar thanks for the quick reply. I am using the latest version of uplink (0.5.5).
 I found a bug in my code, which made this example non-working:
` value = fields.Float()`
Jokes are Strings, not Floats! :)
Changing this, gives me a Joke-Object. 

Is there any way to jump into some error handling in such situations instead of silently returning a dict-object, because the Data does not fit to the Schema?

**Comment by mindrunner** [comment] 2018-08-18 14:04
Ok, now comes the "Collections-Problem". The following code has two tests. One of which gives me the Joke-Object as expected. The other one gives me a List of Dicts, instead a List of Jokes. Whats missing here?

Output:

> <class 'rest_client.lib.model.chuck.Joke.Joke'>
> <class 'dict'>

Expected output:

> <class 'rest_client.lib.model.chuck.Joke.Joke'>
> <class 'rest_client.lib.model.chuck.Joke.Joke'>

```
from marshmallow import Schema, fields, post_load


class Joke(object):
    def __init__(self, id, joke):
        self.id = id
        self.joke = joke


class JokeSchema(Schema):
    id = fields.Int()
    joke = fields.Str()

    @post_load
    def make_joke(self, data):
        return Joke(**data)
```

```
import typing
from uplink import Consumer, \
    get, \
    returns, response_handler, error_handler

from rest_client.lib.model.chuck.Joke import JokeSchema

BASE_URL = "https://api.icndb.com"


@error_handler
def raise_api_error(exc_type, exc_val, exc_tb):
    print("error")


@response_handler
def raise_for_status(response):
    response.raise_for_status()
    return response


@raise_api_error
@raise_for_status
class Chuck(Consumer):

    def __init__(self):
        super().__init__(base_url=BASE_URL)

    @returns.json(member="value")
    @get("jokes/random")
    def get_random_joke(self) -> JokeSchema:
        """Get a random Joke."""

    @returns.json(member="value")
    @get("jokes/random/{count}")
    def get_random_jokes(self, count) -> typing.List[JokeSchema]:
        """Get random Jokes."""
```


```
import unittest

from rest_client.lib.Chuck import Chuck


class ChuckTest(unittest.TestCase):

    chuck = Chuck()

    def test_random_joke(self):
        joke = self.chuck.get_random_joke()
        print(type(joke))

    def test_random_jokes(self):
        jokes = self.chuck.get_random_jokes(10)
        print(type(jokes[0]))


if __name__ == '__main__':
    unittest.main()
```

**Comment by prkumar** [comment] 2018-08-18 18:40
@mindrunner, your example seems to work as expected when I try it locally (I put all the code in one file, that's why it shows `__main__.Joke`):

> <class '__main__.Joke'>
> <class '__main__.Joke'>

Can you print the `dict` object that your second unit test receives from the API?

**Comment by mindrunner** [comment] 2018-08-18 18:44
Thats odd. I also noticed that gitlab CI sometimes gives me different results than local (pycharm / venv) testing.

Modified the test as followes:

```
import unittest

from rest_client.lib.Chuck import Chuck


class ChuckTest(unittest.TestCase):

    chuck = Chuck()

    def test_random_joke(self):
        joke = self.chuck.get_random_joke()
        print(type(joke))

    def test_random_jokes(self):
        jokes = self.chuck.get_random_jokes(10)
        print(type(jokes[0]))
        print(jokes[0])


if __name__ == '__main__':
    unittest.main()
```
Output:

```
<class 'rest_client.lib.model.chuck.Joke.Joke'>
<class 'dict'>
{'id': 348, 'joke': 'There?s an order to the universe: space, time, Chuck Norris.... Just kidding, Chuck Norris is first.', 'categories': []}
```

**Comment by mindrunner** [comment] 2018-08-18 18:45
Not sure how much it matters:
- Arch Linux, fully updated, including a lot of AUR
- Python 3.7
- running in venv with python 3.7 and the following requirements.txt:
```
Django
requests
uplink
oauthlib
requests_oauthlib
pytest
tox
isort
flake8
marshmallow
djangorestframework
markdown
django-filter
```

**Comment by mindrunner** [comment] 2018-08-18 19:02
Gitlab CI output:

```
$ pytest
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.7.2, py-1.5.4, pluggy-0.7.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /builds/ecoincome/backend, inifile: tox.ini
collecting ... collected 6 items

src/lib/rest_client/test/test_Chuck.py::ChuckTest::test_random_joke <class 'rest_client.lib.model.chuck.Joke.Joke'>
PASSED
src/lib/rest_client/test/test_Chuck.py::ChuckTest::test_random_jokes <class 'dict'>
{'id': 219, 'joke': 'Chuck Norris does not own a house. He walks into random houses and people move.', 'categories': []}
PASSED
.
.
.
.
.
.
=========================== 6 passed in 1.80 seconds ===========================
Creating cache default-1...
WARNING: ~/.cache/pip/: no matching files          
Uploading cache.zip to http://runners-cache-4-internal.gitlab.com:444/runner/project/7709037/default-1 
Created cache
Job succeeded
```

**Comment by prkumar** [comment] 2018-08-18 19:16
@mindrunner,  I can't reproduce this on Python 3.7 either. Just to confirm, this happens both on your local machine and on Gitlab CI?

If you can reproduce this locally, we can try to set breakpoints in `uplink` to see why the response is not being deserialized. First, look for the `MarshmallowConverter` class; you can search this in PyCharm using the "Search Everywhere" dialog (i.e., press the "Shift" key twice) and selecting the "Include non-project items" button. Once you find this class, place a breakpoint around line 56 -- the code around here should look like this:

```python
try:
    return self._schema.load(json).data
except MarshmallowConverter.marshmallow.exceptions.MarshmallowError:
   return response
```

Debug your second unit test and see if PyCharm hits this breakpoint. Once here, we can figure out whether `marshmallow` is having trouble deserializing the response.

**Comment by mindrunner** [comment] 2018-08-18 19:51
First unit test hits breakpoint, second does not.

**Comment by mindrunner** [comment] 2018-08-18 19:54
![2018-08-18-215449_1661x195_scrot](https://user-images.githubusercontent.com/1413542/44302844-58013800-a331-11e8-80bb-f514e854fac8.png)

**Comment by mindrunner** [comment] 2018-08-18 19:56
Looks like typing.List is not a marshmallow.Schema. Which I would agree on. Still it should be deserialized. Also odd, that yours is behaving differently.

**Comment by mindrunner** [comment] 2018-08-18 20:36
That works like a charm! :) Thank you for the support.

What is the advantage of 'typing' if I can just use many? Is it restricted to Lists and does not support Diccts, etc?

**Comment by prkumar** [comment] 2018-08-18 21:06
@mindrunner - Great! 😄 

Based on [`marshmallow`'s documentation](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#schema), it seems that `many` is works for lists:
> **many** (*bool*) – Should be set to `True` if obj is a collection so that the object will be serialized to a list.

Also, `typing` is useful when using other serialization frameworks that don't have a feature like `many`.

**Comment by prkumar** [comment] 2018-09-10 21:40
@mindrunner Could you run `provider_details` through `ProviderSchema().load`, instead of `ProviderSchema().make_provide`. It could be that Uplink fails to produce a Provider because `ProviderSchema().load` is complaining for some reason.

**Comment by mindrunner** [comment] 2018-09-10 21:54
This gives me a 'UnmarshalResult' with the following Errors:
{'created_at': ['Not a valid datetime.'], 'updated_at': ['Not a valid datetime.']}

Is that already the problem? But then, why does the get_providers funtion work?

**Comment by prkumar** [comment] 2018-09-10 22:04
@mindrunner - Seems like this is a field validation issue. This happens when the API returns data that doesn't adhere to your Schema (i.e., the `created_at` and `updated_at` fields are not valid datetime objects`.) This cause may relate to the data your sending to the API (e.g., it could be that your sending an unknown `provider_code` in your test). You can print `provider_details["created_at"]` and `provider_details["updated_at"]` to see what the API is returning for these fields.  

As for the  `get_providers` method, the `providers` endpoint must be returning data that adheres to your defined schema.

**Comment by mindrunner** [comment] 2018-09-10 22:09
That pretty much makes sense and is what I thought in the beginning. I compared the data and could not see any difference. I will recheck again and come back here with the results soon! 

Cheers for helping so far. :)

**Comment by prkumar** [comment] 2018-09-10 22:46
@mindrunner - No problem! Just for future reference: we have a [gitter lobby](https://gitter.im/python-uplink/Lobby) where you can ask questions and other concerns, in cases when you're not certain whether what you are experiencing is a bug or not. In my opinion, creating an issue, like this one, is also an equally acceptable medium to discuss concerns like these. So feel free to use either the gitter lobby or the issue tracker as you see fit. 😄 

Also, as [you mentioned](https://github.com/prkumar/uplink/issues/105#issuecomment-414048611) in our discussion on the original issue, I think Uplink should avoid silently returning a `dict` in this scenario. Instead, the `MarshmallowError` should be propagated up for the user to handle appropriately. I'll make the change as part of `v0.6.0`, and hopefully, it will avoid this sort of confusion in the future.

**Comment by mindrunner** [comment] 2018-09-21 18:20
Ok, I dont get it. The Dict I am passing contains datetime objects. So why does 'load(...)' complain about "Not a valid datetime" ?
![2018-09-21-201822_846x198_scrot](https://user-images.githubusercontent.com/1413542/45898929-c2e3da00-bddb-11e8-81ed-45c20455442a.png)
![2018-09-21-201813_950x150_scrot](https://user-images.githubusercontent.com/1413542/45898930-c2e3da00-bddb-11e8-930c-57e4a2666eb1.png)
![2018-09-21-201807_596x295_scrot](https://user-images.githubusercontent.com/1413542/45898932-c2e3da00-bddb-11e8-8047-59d7b84c2688.png)

**Comment by mindrunner** [comment] 2018-09-21 18:29
Hmmm, I tried to uncomment the DateTime fields in my model. Now the 'load(..)' method does not return any error anymore. Howewer, get_provider still returns a dict instead of an Provider object. ;(

**Comment by prkumar** [comment] 2018-09-21 18:31
Hmm... are you on the latest version of Uplink? If not, could you upgrade your Uplink to v0.6.0:

If using `pip`, you can do this with the `-U` option:
```
$ pip install -U uplink
```

**Comment by mindrunner** [comment] 2018-09-21 18:32
Yeah, I just did. I am on 0.6.1 now.

**Comment by mindrunner** [comment] 2018-09-21 18:34
Should't it throw something on a deserialization probel form 0.6.0 on?

**Comment by prkumar** [comment] 2018-09-21 18:34
@mindrunner - It should... are you see the same behavior?

**Comment by mindrunner** [comment] 2018-09-21 18:42
Yeap. With 0.6.1:
```
    def test_list_prov(self):
        provider_details = self.spectre.get_provider("postfinance_ch")

        test2 = ProviderSchema().make_provider(provider_details)
        test = ProviderSchema().load(provider_details)

        print(type(provider_details))
        print(type(test))
        print(type(test2))

```

Output:

```
<class 'dict'>
<class 'marshmallow.schema.UnmarshalResult'>
<class 'rest_client.lib.model.spectre.Provider.Provider'>
```

With unmarshalResult.errors.length == 0

**Comment by prkumar** [comment] 2018-09-21 21:06
@mindrunner - I did some digging and I think I know why you're not getting an exception from Uplink. 

For one, validation errors are not raised when the Schema's `strict` argument is not set to `True` (by default, `strict` is set to `false` for marshmallow v2.x). So, if you want validation to be enforced on deserialization, you would need to do `ProviderSchema(strict=True)`. 

Second, to figure out what's going on behind `spectre.get_provider`, I'd recommend setting a breakpoint on line 55 of `uplink.converters.marshmallow_.py`, and inspecting what the value `created_at` and `updated_at` are before they are ran through `schema.load` on line 55 (the `json` variable should contain the response body):

![screen shot 2018-09-21 at 2 05 07 pm](https://user-images.githubusercontent.com/10181244/45906006-65ce3100-bda7-11e8-8b2d-d4fbba1cdb70.png)

**Comment by mindrunner** [comment] 2018-09-27 11:14
@prkumar Thank you for all the help. This time, it is actually on me. I had a typo/missing field in my Data Model. 

Fixed version:
```
class Provider(object):
    def __init__(self, id, code, name, mode, status, automatic_fetch, customer_notified_on_sign_in, interactive,
                 identification_mode, instruction, home_url, login_url, logo_url, country_code,
                 refresh_timeout, holder_info, created_at, updated_at, max_consent_days=0, forum_url="",
                 required_fields=[], interactive_fields=[]):
        self.id = id
        self.code = code
        self.name = name
        self.mode = mode
        self.status = status
        self.automatic_fetch = automatic_fetch
        self.customer_notified_on_sign_in = customer_notified_on_sign_in
        self.interactive = interactive
        self.identification_mode = identification_mode
        self.instruction = instruction
        self.home_url = home_url
        self.login_url = login_url
        self.forum_url = forum_url
        self.logo_url = logo_url
        self.county_code = country_code
        self.refresh_timeout = refresh_timeout
        self.holder_info = holder_info
        self.max_consent_days = max_consent_days
        self.created_at = created_at
        self.updated_at = updated_at
        self.required_fields = required_fields
        self.interactive_fields = interactive_fields


class ProviderSchema(Schema):
    id = fields.Str(required=True)
    code = fields.Str()
    name = fields.Str()
    mode = fields.Str()
    status = fields.Str()
    automatic_fetch = fields.Bool()
    customer_notified_on_sign_in = fields.Bool()
    interactive = fields.Bool()
    identification_mode = fields.Str()
    instruction = fields.Str()
    home_url = fields.Str()
    login_url = fields.Str()
    forum_url = fields.Str()
    logo_url = fields.Str()
    country_code = fields.Str()
    refresh_timeout = fields.Int()
    holder_info = fields.List(fields.Str())
    max_consent_days = fields.Int(required=False, allow_none=True, default=0)
    created_at = fields.Str()
    updated_at = fields.Str()
    required_fields = fields.List(fields.Raw(), required=False, allow_none=True, default=[])
    interactive_fields = fields.List(fields.Raw(), required=False, allow_none=True, default=[])

    @post_load
    def make_provider(self, data):
        return Provider(**data)
```

What is the best way here to have optional fields? Even if I set required=false, allow_none=true,default=... I have problems when not setting a default value in the constructor. Am I overlooking something here? Or is that expected behaviour / best practice?

Cheers
Lukas

**Comment by prkumar** [comment] 2018-10-09 18:32
@mindrunner - I'm going to go ahead and close this. Please let me know if you are facing any other issues! Thanks.

**Closed by prkumar** 2018-10-09 18:32 UTC
Labels: Question
